<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_Attribute extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'attribute', array('name','ascii_id','created','created_by'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->fields[$key] = $value;
			}
		}
	}
    public function getName() { return $this->fields["name"]; }
    public function getAscii_id() { return $this->fields["ascii_id"]; }
    public function getCreated() { return $this->fields["created"]; }
    public function getCreated_by() { return $this->fields["created_by"]; }
}