<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_ItemsetItem extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'itemset_item', array('itemset_id','item_id','created','sort_order'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
    public function getItemset_id() { return $this->itemset_id; }
    public function getItem_id() { return $this->item_id; }
    public function getCreated() { return $this->created; }
    public function getSort_order() { return $this->sort_order; }
}