<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_Itemset extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'itemset', array('name','title','created','created_by'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
    public function getName() { return $this->name; }
    public function getTitle() { return $this->title; }
    public function getCreated() { return $this->created; }
    public function getCreated_by() { return $this->created_by; }
}