<?php

require_once 'Dase/DBO.php';

/*
 * DO NOT EDIT THIS FILE
 * it is auto-generated by the
 * script 'bin/class_gen.php
 * 
 */

class Dase_DBO_Autogen_User extends Dase_DBO 
{
	public function __construct($db,$assoc = false) 
	{
		parent::__construct($db,'user', array('eid','name','email','is_admin'));
		if ($assoc) {
			foreach ( $assoc as $key => $value) {
				$this->$key = $value;
			}
		}
	}
    public function getEid() { return $this->eid; }
    public function getName() { return $this->name; }
    public function getEmail() { return $this->email; }
    public function getIs_admin() { return $this->is_admin; }
}